class Command:
    VerdantSpotStart = "@VS"
    NextLayer = "@NL"
    Name = "@NM"
    Desctiption = "@DS"
    Author = "@AU"
    BorderLeft = "@BL"
    BorderTop = "@BT"
    BorderRight = "@BR"
    BorderBottom = "@BB"
    LayerEntry = "@LE"
    KindEntry = "@KE"
    ProcessDictionaries = "@DE"
    Object = "@OB"
    Point = "@PT"
    Stop = "@FN"