class VCommand:
    VerdantSpotStart = "@VS"
    NextLayer = "@NL"
    Name = "@NM"
    Desctiption = "@DS"
    Author = "@AU"
    MapSize = "@MS"
    Center = "@CT"
    LayerEntry = "@LE"
    KindEntry = "@KE"
    ProcessDictionaries = "@DE"
    Object = "@OB"
    Point = "@PT"
    Stop = "@FN"